export default {
  id: {
    title: '主键Id',
    dataIndex: 'id',
    sorter: false,
    showSorterTooltip: false,
    ellipsis: true,
    width: 80,
  },
  iosMinVersion: {
    title: 'ios最新版本',
    dataIndex: 'iosMinVersion',
    sorter: false,
    showSorterTooltip: false,
    ellipsis: true,
    width: 110,
  },
  iosCurrentVersion: {
    title: 'ios最小版本',
    dataIndex: 'iosCurrentVersion',
    sorter: false,
    showSorterTooltip: false,
    ellipsis: true,
    width: 110,
  },
  iosDownloadUrl: {
    title: 'ios路径',
    dataIndex: 'iosDownloadUrl',
    sorter: false,
    showSorterTooltip: false,
    ellipsis: true,
    width: 110,
  },
  androidMd5: {
    title: '安卓MD5',
    dataIndex: 'androidMd5',
    sorter: false,
    showSorterTooltip: false,
    ellipsis: true,
    width: 0,
  },
  iosCurrentVersionDesc: {
    title: 'ios更新描述',
    dataIndex: 'iosCurrentVersionDesc',
    sorter: false,
    showSorterTooltip: false,
    ellipsis: true,
    width: 110,
  },
  androidMinVersion: {
    title: 'android最新版本',
    dataIndex: 'androidMinVersion',
    sorter: false,
    showSorterTooltip: false,
    width: 150,
  },
  androidCurrentVersion: {
    title: 'android最小版本',
    dataIndex: 'androidCurrentVersion',
    sorter: false,
    showSorterTooltip: false,
    ellipsis: true,
    width: 130,
  },
  androidDownloadUrl: {
    title: 'android路径',
    dataIndex: 'androidDownloadUrl',
    sorter: false,
    showSorterTooltip: false,
    ellipsis: true,
    width: 110,
  },
  androidCurrentVersionDesc: {
    title: 'android更新描述',
    dataIndex: 'androidCurrentVersionDesc',
    sorter: false,
    showSorterTooltip: false,
    ellipsis: true,
    width: 130,
  },
  createTime: {
    title: '创建时间',
    dataIndex: 'createTime',
    sorter: false,
    showSorterTooltip: false,
    ellipsis: true,
    width: 110,
  },
};
