export default {
  id: {
    title: 'ID',
    dataIndex: 'id',
    ssorter: false,
    showSorterTooltip: false,
    ellipsis: true,
    width: 110,
    float: 'left',
  },
  companyNum: {
    title: '公司编码',
    dataIndex: 'companyNum',
    sorter: false,
    showSorterTooltip: false,
    ellipsis: true,
    width: 110,
    float: 'left',
  },
  appyid: {
    title: '应用ID',
    dataIndex: 'appyid',
    sorter: false,
    showSorterTooltip: false,
    ellipsis: true,
    width: 110,
    float: 'left',
  },
  appName: {
    title: '应用名称',
    dataIndex: 'appName',
    sorter: false,
    showSorterTooltip: false,
    ellipsis: true,
    width: 110,
    float: 'left',
  },
  menuid: {
    title: '菜单ID',
    dataIndex: 'menuid',
    sorter: false,
    showSorterTooltip: false,
    ellipsis: true,
    width: 110,
    float: 'left',
  },
  menuName: {
    title: '菜单名称',
    dataIndex: 'menuName',
    sorter: false,
    showSorterTooltip: false,
    ellipsis: true,
    width: 110,
    float: 'left',
  },
};
