export const TABLE_HEADER = {
  companyNum: {
    title: '公司编码',
    dataIndex: 'companyNum',
    sorter: false,
    showSorterTooltip: false,
    ellipsis: true,
    width: 110,
    float: 'left',
  },
  userId: {
    title: 'userId',
    dataIndex: 'userId',
    sorter: false,
    showSorterTooltip: false,
    width: 80,
    ellipsis: true,
    float: 'left',
  },
  userName: {
    title: '用户名称',
    dataIndex: 'userName',
    sorter: false,
    showSorterTooltip: false,
    width: 110,
    ellipsis: true,
    float: 'left',
  },
  userAgent: {
    title: '用户代理信息',
    dataIndex: 'userAgent',
    sorter: false,
    showSorterTooltip: true,
    width: 110,
    ellipsis: true,
    float: 'left',
  },
  createTime: {
    title: '创建时间',
    dataIndex: 'createTime',
    sorter: false,
    showSorterTooltip: false,
    width: 110,
    ellipsis: true,
    float: 'left',
  },
  menuName: {
    title: '菜单名称',
    dataIndex: 'menuName',
    sorter: false,
    showSorterTooltip: false,
    width: 110,
    ellipsis: true,
    float: 'left',
  },
  menuCode: {
    title: '菜单编码',
    dataIndex: 'menuCode',
    sorter: false,
    showSorterTooltip: false,
    width: 110,
    ellipsis: true,
    float: 'left',
  },
  menuPath: {
    title: '菜单路径',
    dataIndex: 'menuPath',
    sorter: false,
    showSorterTooltip: false,
    width: 110,
    ellipsis: true,
    float: 'left',
  },
  menuType: {
    title: '菜单类型',
    dataIndex: 'menuType',
    sorter: false,
    showSorterTooltip: false,
    width: 80,
    ellipsis: true,
    float: 'left',
  },
  method: {
    title: '请求方式',
    dataIndex: 'method',
    sorter: false,
    showSorterTooltip: false,
    width: 110,
    ellipsis: true,
    float: 'left',
  },
  param: {
    title: '请求参数',
    dataIndex: 'param',
    sorter: false,
    showSorterTooltip: false,
    width: 110,
    ellipsis: true,
    float: 'left',
  },
  remoteAddress: {
    title: 'IP地址',
    dataIndex: 'remoteAddress',
    sorter: false,
    showSorterTooltip: false,
    width: 110,
    ellipsis: true,
    float: 'left',
  },
  source: {
    title: '来源',
    dataIndex: 'source',
    sorter: false,
    showSorterTooltip: false,
    width: 110,
    ellipsis: true,
    float: 'left',
  },
};
