export const data1 = [
  {
    colName: 'eam风机编号',
    colType: 'SELECT',
    dataIndex: 'assetNum',
    placeholder: '',
    width: 120,
    message: '不能为空',
    tip: true,
  },
  {
    colName: 'eam部门编码',
    colType: 'input',
    dataIndex: 'deptNum',
    placeholder: '',
    message: '不能为空',
    width: 120,
    tip: true,
  },
  {
    colName: '集控设备编号',
    colType: 'input',
    dataIndex: 'deviceId',
    placeholder: '',
    width: 120,
    message: '不能为空',
    tip: true,
  },
  {
    colName: '创建人',
    colType: 'input',
    dataIndex: 'creator',
    placeholder: '',
    width: 120,
    message: '不能为空',
    tip: true,
  },
  {
    colName: '创建时间',
    colType: 'input',
    dataIndex: 'createTime',
    placeholder: '',
    width: 120,
    verificationType: 'number',
    minnumber: 1,
    message: '不能为空',
    tip: true,
  },
];

export const data2 = [
  {
    colName: 'ID',
    colType: 'input',
    dataIndex: 'id',
    edit: true,
    placeholder: '',
    width: 120,
    tip: true,
  },
  {
    colName: 'AGC设备编码',
    colType: 'input',
    dataIndex: 'agc_device_id',
    edit: true,
    placeholder: '',
    width: 120,
    tip: true,
  },
  {
    colName: '集控编码',
    colType: 'input',
    dataIndex: 'contro_num',
    edit: true,
    placeholder: '',
    width: 120,
    tip: true,
  },
];
