export default {
  id: {
    title: 'ID',
    dataIndex: 'id',
    sorter: false,
    showSorterTooltip: false,
    width: 80,
  },
  createBy: {
    title: '创建人',
    dataIndex: 'createBy',
    sorter: false,
    showSorterTooltip: false,
    width: 130,
  },
  createTime: {
    title: '创建时间',
    dataIndex: 'createTime',
    sorter: false,
    showSorterTooltip: false,
    width: 130,
  },
  description: {
    title: '描述',
    dataIndex: 'description',
    sorter: false,
    showSorterTooltip: false,
    width: 100,
  },
  modifyBy: {
    title: '修改人',
    dataIndex: 'modifyBy',
    sorter: false,
    showSorterTooltip: false,
    width: 130,
  },
  modifyTime: {
    title: '修改时间',
    dataIndex: 'modifyTime',
    sorter: false,
    showSorterTooltip: false,
    width: 130,
  },
  tokenPrefix: {
    title: 'token前缀',
    dataIndex: 'tokenPrefix',
    sorter: false,
    showSorterTooltip: false,
    width: 130,
  },
  url: {
    title: '路径',
    dataIndex: 'url',
    sorter: false,
    showSorterTooltip: false,
    width: 130,
  },
};
