export const data1 = [
  {
    colName: '菜单编码',
    colType: 'input',
    dataIndex: 'menuCode',
    placeholder: '',
    width: 230,
    lookWidth: 230,
    message: '不能为空',
    tip: true,
  },
  {
    colName: '上级菜单ID',
    colType: 'select',
    dataIndex: 'parentId',
    placeholder: '',
    width: 200,
    lookWidth: 150,
    message: '不能为空',
    tip: true,
  },
  {
    colName: '菜单/按钮名称',
    colType: 'input',
    dataIndex: 'menuName',
    placeholder: '',
    message: '不能为空',
    width: 160,
    lookWidth: 180,
    tip: true,
  },
  {
    colName: 'type选择',
    colType: 'SELECT',
    dataIndex: 'type',
    placeholder: '',
    width: 150,
    lookWidth: 100,
    message: '不能为空',
    tip: true,
  },
  {
    colName: '权限选择',
    colType: 'powerId',
    dataIndex: 'powerId',
    placeholder: '',
    width: 205,
    lookWidth: 130,
    message: '不能为空',
    tip: false,
  },
  {
    colName: 'component',
    colType: 'input',
    dataIndex: 'component',
    placeholder: '',
    width: 200,
    lookWidth: 200,
    message: '不能为空',
    tip: false,
  },
  {
    colName: '描述',
    colType: 'input',
    dataIndex: 'description',
    placeholder: '',
    width: 150,
    lookWidth: 160,
    message: '不能为空',
    tip: false,
  },
  {
    colName: '图标',
    colType: 'input',
    dataIndex: 'icon',
    placeholder: '',
    message: '不能为空',
    width: 180,
    lookWidth: 180,
    tip: false,
  },
  {
    colName: '对应路由path',
    colType: 'input',
    dataIndex: 'menupath',
    placeholder: '',
    width: 220,
    lookWidth: 220,
    message: '不能为空',
    tip: false,
  },
  {
    colName: '排序',
    colType: 'input',
    dataIndex: 'orderNum',
    placeholder: '请输入数字',
    message: '不能为空',
    width: 100,
    lookWidth: 100,
    tip: false,
  },
  {
    colName: '权限标识',
    colType: 'input',
    dataIndex: 'perms',
    placeholder: '',
    width: 140,
    lookWidth: 140,
    message: '不能为空',
    tip: false,
  },
  {
    colName: '系统来源',
    colType: 'input',
    dataIndex: 'source',
    placeholder: '',
    width: 110,
    lookWidth: 100,
    message: '不能为空',
    tip: true,
  },
];

export const data2 = [
  {
    colName: '资源编码',
    colType: 'input',
    dataIndex: 'resourcesCode',
    edit: true,
    placeholder: '',
    width: 120,
    lookWidth: '20%',
    tip: true,
  },
  {
    colName: '资源描述',
    colType: 'input',
    dataIndex: 'resourcesDescription',
    edit: true,
    placeholder: '',
    width: 120,
    lookWidth: '25%',
    tip: true,
  },
  {
    colName: '资源名称',
    colType: 'input',
    dataIndex: 'resourcesName',
    edit: true,
    placeholder: '',
    width: 120,
    lookWidth: '25%',
    tip: true,
  },
  {
    colName: '对应路由path',
    colType: 'input',
    dataIndex: 'resourcesPath',
    edit: true,
    placeholder: '',
    width: 120,
    lookWidth: '30%',
    tip: true,
  },
];
