export default [
  {
    title: '登录页',
    path: '/user',
    component: '@/layouts/UserLayout',
    routes: [
      {
        title: '登录',
        name: 'login',
        path: '/user/login',
        component: './User/login',
      },
      { path: '/404', component: './404' },
    ],
  },
  {
    path: '/',
    component: '@/layouts/BasicLayout',
    title: '业务页面',
    routes: [
      { path: '/', component: '@/pages/index' },
      { path: '/dashboard', component: './Dashboard' },
      { path: '/backstageManagement/appmanaga', component: './AppManaga', title: '应用菜单管理' },
      { path: '/backstageManagement/dictionaries', component: './Dictionaries', title: '数据字典' },
      { path: '/sheBeiTaiZhangZiDianManage', component: './Dictionaries', title: 'EAM数据字典' },
      { path: '/backstageManagement/measures', component: './Measures', title: '计划措施' },
      { path: '/backstageManagement/appversions', component: './AppVersions', title: 'APP版本升级' },
      { path: '/backstageManagement/dataAnalysis', component: './DataAnalysis', title: '数据分析' },
      { path: '/backstageManagement/webToken', component: './ExernarToken', title: '外部token' },
      { path: '/backstageManagement/loganalysis', component: './LogAnalysis', title: '日志分析' },
      { path: '/backstageManagement/stationMap', component: './StationMap', title: '场站映射' },
      { path: '/backstageManagement/tenantapplication', component: './TenantApplication', title: '租户应用' },
      { path: '/backstageManagement/timedTask', component: './TimedTask', title: '定时任务' },
      { path: '/backstageManagement/feedback', component: './Retroaction', title: '问题反馈' },
      { path: '/backstageManagement/Interface', component: './Interface', title: '用户分析' },
      { path: '/announcementManagement', component: './Notice', title: '公告管理' },
      { path: '/backstageManagement/serviceTeam', component: './ServiceTeam', title: '大群服务团队' },
      { path: '/backstageManagement/stationrule', component: './StationRule', title: '大群场站规则' },
      { path: '/backstageManagement/staffing', component: './Staffing', title: '岗位配置' },
      { path: '/backstageManagement/userManagement', component: './UserManagement', title: '用户管理' },
      { path: '/backstageManagement/roleManagement', component: './RoleManage', title: '角色管理' },
      { path: '/iconfont', component: './Iconfont', title: '导航图标配置' },
      { path: '/CanalConnectManage', component: './Canal/index', title: 'canal链接管理' },
      { path: '/IndexInfoManage', component: './Canal/index', title: '索引信息配置管理' },
      { path: '/dataInfo', component: './IOTData', title: 'IOT数据接入配置' },
      { path: '/LiveAccess', component: './LiveAccess', title: '现场数据接入配置' },
      { path: '/auxiliaryServiceConfiguration', component: './auxiliaryService', title: '辅助服务'},
      { path: '/DataDecisionSystem', component: './DataDecisionSystem', title: '数据决策系统' },
      { path: '/404', component: './404' },
    ],
  },
  { path: '/404', component: './404' },
];
