export default {
  id: {
    title: 'ID',
    dataIndex: 'id',
    sorter: false,
    showSorterTooltip: false,
    width: 80,
  },
  control_center: {
    title: '集控运营中心',
    dataIndex: 'control_center',
    sorter: false,
    showSorterTooltip: false,
    width: 130,
  },
  dept_num: {
    title: 'eam期编号',
    dataIndex: 'dept_num',
    sorter: false,
    showSorterTooltip: false,
    width: 130,
  },
  dept_id: {
    title: '部门Id',
    dataIndex: 'dept_id',
    sorter: false,
    showSorterTooltip: false,
    width: 100,
  },
  control_num: {
    title: '集控风场编号',
    dataIndex: 'control_num',
    sorter: false,
    showSorterTooltip: false,
    width: 130,
  },
  dept_name: {
    title: 'eam期名称',
    dataIndex: 'dept_name',
    sorter: false,
    showSorterTooltip: false,
    width: 130,
  },
  eam_project: {
    title: '实时中的期数',
    dataIndex: 'eam_project',
    sorter: false,
    showSorterTooltip: false,
    width: 130,
  },
  control_name: {
    title: '集控风场名称',
    dataIndex: 'control_name',
    sorter: false,
    showSorterTooltip: false,
    width: 130,
  },
  eam_name: {
    title: 'eam场名称',
    dataIndex: 'eam_name',
    sorter: false,
    showSorterTooltip: false,
    width: 130,
  },
  eam_trans_project_name: {
    title: 'EAM中的期',
    dataIndex: 'eam_trans_project_name',
    sorter: false,
    showSorterTooltip: false,
    width: 130,
  },
  source: {
    title: '数据来源',
    dataIndex: 'source',
    sorter: false,
    showSorterTooltip: false,
    width: 130,
  },
  eam_num: {
    title: 'eam风场编号',
    dataIndex: 'eam_num',
    sorter: false,
    showSorterTooltip: false,
    width: 130,
  },
  send_flag: {
    title: '是否生成xml',
    dataIndex: 'send_flag',
    sorter: false,
    showSorterTooltip: false,
    width: 200,
  },
};
