export let config = [
  {
    name: '抢单任务无人响应时长设置(min)',
    detil: 'rule2',
    tip: true,
    defaultValue: 600,
    verificationType: 'number',
    minnumber: 10,
    tips:
      '用来设置派发方式是抢单的工单，无人接单超时的时长。超过该时长后工单将派发失败并回到管家处',
    min: 10,
    placeholder: '请输入抢单任务无人响应时长设置',
  },
  {
    name: '派单任务无人响应时长设置(min)',
    detil: 'rule1',
    tip: true,
    verificationType: 'number',
    minnumber: 10,
    placeholder: '请输入派单任务无人响应时长设置',
    defaultValue: 600,
    tips:
      '用来设置派发方式是派单的工单，无人接单超时的时长。超过该时长后工单将自动派发给下一个风光侠。当所有风光侠都超时未接收时，将返回到管家处。',
  },
  {
    name: '派单距离(m)',
    detil: 'distance',
    tip: true,
    verificationType: 'number',
    minnumber: 10,
    defaultValue: 1000,
    placeholder: '请输入派单距离',
    tips: '是指工单以派单方式时优先派发的设置在距离内的风光侠',
  },
  {
    name: '超时分比例(%)',
    detil: 'timeoutRate',
    tip: true,
    point: 1,
    verificationType: 'float',
    isZero: true,
    minnumber: 0,
    placeholder: '请输入超时分比例',
    maxnumber: 100,
    defaultValue: 90,
    tips:
      '是指当工单工作的实际处理时长超过工作规定的时间范围后，工作规定价格支付给风光侠的价格比例',
  },
  {
    name: '税率(%)',
    detil: 'taxRate',
    tip: true,
    point: 2,
    placeholder: '请输入税率',
    verificationType: 'number',
    minnumber: 0,
    isZero: true,
    defaultValue: 0.6,
    tips: '用于设置工单费用中包含的税率',
  },
  {
    name: '收入分配比例(%)',
    detil: 'incomeRate',
    tip: true,
    placeholder: '请输入收入分配比例',
    verificationType: 'number',
    minnumber: 0,
    isZero: true,
    maxnumber: 100,
    defaultValue: 40,
    tips:
      '用于设置工单对应工作的标准费用支付给风光侠的比例。如设置40%即工单支付费用的40%用于风光侠的收入',
  },
  {
    name: '积分奖励比例(%)',
    detil: 'integralRewardRate',
    tip: true,
    verificationType: 'number',
    minnumber: 0,
    isZero: true,
    placeholder: '请输入积分奖励比例',
    defaultValue: 1,
    tips: '用于设置风光侠积分对应收入的比例。如配置1%，假设收入100元，对应积分为1积分',
  },
  {
    name: '标准小时费率(元/h)',
    detil: 'stdcostsHours',
    tip: true,
    point: 2,
    verificationType: 'float',
    minnumber: 0,
    placeholder: '请输入标准小时费率',
    isZero: true,
    defaultValue: 60,
    tips: '用于设置本场站的风光侠小时费率。按人数及工时派发计划工作时将以该费用进行工单费用的计算',
  },
  {
    name: '计划奖励金额(元)',
    detil: 'planRewardAmount',
    tip: true,
    verificationType: 'number',
    minnumber: 0,
    placeholder: '请输入计划奖励金额',
    isZero: true,
    defaultValue: 50,
    tips: '用于设置计划工单的单次奖励金额；',
  },
  {
    name: '非计划奖励金额(元)',
    detil: 'rewardAmount',
    tip: true,
    verificationType: 'number',
    minnumber: 0,
    placeholder: '请输入非计划奖励金额',
    isZero: true,
    defaultValue: 230,
    tips: '用于设置非计划工单的单次奖励金额',
  },
  {
    name: '计划奖励周期(天)',
    detil: 'planRewardCycle',
    tip: true,
    placeholder: '请输入计划奖励周期',
    verificationType: 'number',
    minnumber: 1,
    defaultValue: 30,
    tips: '用于设置计划工单的奖励周期',
  },
  {
    name: '非计划奖励周期(天)',
    detil: 'rewardCycle',
    tip: true,
    placeholder: '请输入非计划奖励周期',
    verificationType: 'number',
    minnumber: 0,
    isZero: true,
    defaultValue: 30,
    tips: '用于设置非计划工单的奖励周期',
  },
  {
    name: '计划奖励比例(%)',
    detil: 'planRewardRate',
    tip: true,
    verificationType: 'number',
    minnumber: 0,
    placeholder: '请输入计划奖励比例',
    isZero: true,
    maxnumber: 100,
    defaultValue: 40,
    tips: '用于设置计划/非计划工单奖励费用中支付给风光侠的比例',
  },
  {
    name: '非计划奖励比例(%)',
    detil: 'rewardRate',
    tip: true,
    placeholder: '请输入非计划奖励比例',
    verificationType: 'number',
    minnumber: 0,
    isZero: true,
    maxnumber: 100,
    defaultValue: 40,
    tips: '非计划工作满足工单奖励是分配风光侠的奖励金额比例；',
  },
  {
    name: '计划奖励次数(次)',
    detil: 'planRewardNum',
    tip: true,
    placeholder: '请输入计划奖励次数',
    verificationType: 'number',
    minnumber: 0,
    isZero: true,
    defaultValue: 1,
    tips:
      '完成计划工单后,在奖励周期内故障没有复现而奖励的次数。例如奖励周期设置30天,奖励次数设置2次,那么30天奖励一次,60天奖励一次。',
  },
  {
    name: '非计划奖励次数(次)',
    detil: 'rewardNum',
    tip: true,
    placeholder: '请输入非计划奖励次数',
    verificationType: 'number',
    minnumber: 0,
    isZero: true,
    defaultValue: 1,
    tips:
      '完成非计划工单后,在奖励周期内故障没有复现而奖励的次数。例如奖励周期设置30天,奖励次数设置2次,那么30天奖励一次,60天奖励一次。',
  },
  {
    name: '惩罚周期(天)',
    detil: 'penaltyCycle',
    tip: true,
    placeholder: '请输入惩罚周期',
    verificationType: 'number',
    minnumber: 1,
    defaultValue: 7,
    tips: '对于非计划工单当在设置的惩罚周期内风机发生故障时对应工单的派发费用将扣除',
  },
];

export let Mockdata = {
  rule2: '600',
  rule1: '600',
  distance: '1000',
  timeoutRate: '90',
  taxRate: '60',
  incomeRate: '40',
  rewardRate: '40',
  integralRewardRate: '40',
  planRewardAmount: '50',
  rewardAmount: '230',
  unplanProportion: '50',
  planRewardCycle: '30',
  rewardCycle: '30',
  planRewardRate: '40',
  penaltyCycle: '7',
  incomeDistributionRatio: '78',
  planRewardNum: '1',
  rewardNum: '1',
};
