export const column = [
  {
    colName: '部门编码',
    colType: 'input',
    dataIndex: 'deptNum',
    placeholder: '请输入数字',
    width: 160,
    message: '不能为空',
    tip: true,
  },
  {
    colName: '部门名称',
    colType: 'input',
    dataIndex: 'deptName',
    placeholder: '',
    width: 160,
    message: '不能为空',
    tip: true,
  },
  {
    colName: '项目期数',
    colType: 'select',
    dataIndex: 'project',
    placeholder: '',
    width: 160,
    message: '不能为空',
    tip: false,
  },
  {
    colName: '简称',
    colType: 'input',
    dataIndex: 'abbreviate',
    placeholder: '',
    width: 160,
    message: '不能为空',
    tip: true,
  },
  {
    colName: '简称编码',
    colType: 'input',
    dataIndex: 'abbreviateCode',
    placeholder: '',
    width: 160,
    message: '不能为空',
    tip: false,
  },
  {
    colName: '是否有效',
    colType: 'select',
    dataIndex: 'valid',
    placeholder: '',
    width: 160,
    message: '不能为空',
    tip: false,
  },
  {
    colName: '资管标签',
    colType: 'select',
    dataIndex: 'zgLabel',
    placeholder: '',
    width: 160,
    message: '不能为空',
    tip: true,
  },
  {
    colName: '客户标签',
    colType: 'select',
    dataIndex: 'khLabel',
    placeholder: '',
    width: 160,
    message: '不能为空',
    tip: true,
  },
  {
    colName: '项目类型',
    colType: 'select',
    dataIndex: 'projectType',
    placeholder: '',
    width: 160,
    message: '不能为空',
    tip: false,
  },
  {
    colName: '地区',
    colType: 'input',
    dataIndex: 'region',
    placeholder: '',
    width: 160,
    message: '不能为空',
    tip: true,
  },
  {
    colName: '装机台数',
    colType: 'input',
    dataIndex: 'fdczjCount',
    placeholder: '',
    width: 160,
    message: '不能为空',
    tip: false,
  },
  {
    colName: '风电场地址',
    colType: 'input',
    dataIndex: 'windFarmLocation',
    placeholder: '',
    width: 160,
    message: '不能为空',
    tip: false,
  },
  {
    colName: '经度',
    colType: 'input',
    dataIndex: 'longitude',
    placeholder: '',
    width: 160,
    message: '不能为空',
    tip: false,
  },
  {
    colName: '维度',
    colType: 'input',
    dataIndex: 'latitude',
    placeholder: '',
    width: 160,
    message: '不能为空',
    tip: false,
  },
  {
    colName: '合同容量',
    colType: 'input',
    dataIndex: 'contractCapacity',
    placeholder: '',
    width: 160,
    message: '不能为空',
    tip: false,
  },
  {
    colName: '风功率预测系统厂家',
    colType: 'input',
    dataIndex: 'powerForecastFactory',
    placeholder: '',
    width: 160,
    message: '不能为空',
    tip: false,
  },
  {
    colName: '能巢版本',
    colType: 'input',
    dataIndex: 'nengchaoVersion',
    placeholder: '',
    width: 160,
    message: '不能为空',
    tip: false,
  },
  {
    colName: '移交生产时间',
    dataIndex: 'transProductionTime',
    placeholder: '',
    width: 160,
    message: '不能为空',
    tip: false,
  },
  {
    colName: '能巢布置时间',
    dataIndex: 'nengchaoTime',
    placeholder: '',
    width: 160,
    message: '不能为空',
    tip: false,
  },
  {
    colName: '部门区域',
    colType: 'input',
    dataIndex: 'deptArea',
    placeholder: '',
    width: 160,
    message: '不能为空',
    tip: false,
  },
  {
    colName: '所属集控',
    colType: 'select',
    dataIndex: 'centralControl',
    placeholder: '',
    width: 160,
    message: '不能为空',
    tip: false,
  },
  {
    colName: '所属虚拟场站',
    colType: 'select',
    dataIndex: 'storedEnergy',
    placeholder: '',
    width: 160,
    message: '不能为空',
    tip: false,
  },
  {
    colName: 'lot数据源配置',
    colType: 'button',
    dataIndex: 'phaseConfig',
    width: 160,
    message: '不能为空',
    tip: false,
  },
];

export const data2 = [
  {
    colType: 'show',
    dataIndex: '',
    width: 30,
  },
  {
    colName: '部门编号',
    colType: 'input',
    dataIndex: 'deptNum',
    edit: true,
    placeholder: '',
    width: 120,
    tip: true,
  },
  {
    colName: '期数',
    colType: 'select',
    dataIndex: 'project',
    edit: true,
    placeholder: '',
    width: 120,
    tip: true,
  },
  {
    colName: '场站名称',
    colType: 'input',
    dataIndex: 'deptName',
    edit: true,
    placeholder: '',
    width: 120,
    tip: false,
  },
  {
    colName: '地区',
    colType: 'input',
    dataIndex: 'region',
    edit: true,
    placeholder: '',
    width: 120,
    tip: false,
  },
];
