export const data1 = [
  {
    colName: '菜单编码',
    colType: 'input',
    dataIndex: 'menuCode',
    placeholder: '',
    width: 160,
    message: '不能为空',
    tip: true,
  },
  {
    colName: '上级菜单ID',
    colType: 'select',
    dataIndex: 'parentId',
    placeholder: '',
    width: 200,
    message: '不能为空',
    tip: true,
  },
  {
    colName: '菜单/按钮名称',
    colType: 'input',
    dataIndex: 'menuName',
    placeholder: '',
    message: '不能为空',
    width: 120,
    tip: true,
  },
  {
    colName: 'type选择',
    colType: 'SELECT',
    dataIndex: 'type',
    placeholder: '',
    width: 100,
    message: '不能为空',
    tip: true,
  },
  {
    colName: '对应路由path',
    colType: 'input',
    dataIndex: 'component',
    placeholder: '',
    width: 160,
    message: '不能为空',
    tip: true,
  },

  {
    colName: '描述',
    colType: 'input',
    dataIndex: 'description',
    placeholder: '',
    width: 140,
    message: '不能为空',
    tip: false,
  },
  {
    colName: '图标',
    colType: 'input',
    dataIndex: 'icon',
    placeholder: '',
    message: '不能为空',
    width: 160,
    tip: false,
  },
  {
    colName: '对应路由path',
    colType: 'input',
    dataIndex: 'menupath',
    placeholder: '',
    width: 180,
    message: '不能为空',
    tip: false,
  },
  {
    colName: '排序',
    colType: 'input',
    dataIndex: 'orderNum',
    placeholder: '请输入数字',
    message: '不能为空',
    width: 100,
    tip: false,
  },
  {
    colName: '权限标识',
    colType: 'input',
    dataIndex: 'perms',
    placeholder: '',
    width: 140,
    message: '不能为空',
    tip: false,
  },
  {
    colName: '系统来源',
    colType: 'input',
    dataIndex: 'source',
    placeholder: '',
    width: 100,
    message: '不能为空',
    tip: true,
  },
];
